# Generated by Django 2.2.3 on 2019-10-24 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knuckledragger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='authored_by',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='MailingList',
        ),
        migrations.RemoveField(
            model_name='room',
            name='authored_by',
        ),
        migrations.DeleteModel(
            name='Character',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
