# Generated by Django 2.2.3 on 2019-09-28 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knuckledragger', '0002_auto_20190928_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brawny', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Arrivad', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('age', models.IntegerField(default=0)),
                ('hit_points', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=16)),
                ('speed', models.IntegerField(default=0)),
                ('attributes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knuckledragger.Attributes')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knuckledragger.Races')),
            ],
        ),
        migrations.CreateModel(
            name='Brawny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knuckledragger.Type')),
            ],
        ),
    ]
