# Generated by Django 2.2.3 on 2019-10-12 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('knuckledragger', '0007_auto_20191009_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=16)),
                ('description', models.CharField(max_length=200)),
                ('authored_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='knuckledragger.Character')),
            ],
        ),
    ]
